export const GETINFO = "INFO"
export const LOGIN = "LOGIN"
export const GETPROFILE = "GETPROFILE"
export const GETAUTHOR = "GETAUTHOR"
export const GETQUOTE = "GETQUOTE"
export const LOGOUT = "LOGOUT"
